name: Publish

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@master
        with:
          source-folder: website
          git-user: bot
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
